/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sudoku;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
    	int initial[][] = 
		   {{5,3,0,  0,7,0,  0,0,0},
			{6,0,0,  1,9,5,  0,0,0},
			{0,9,8,  0,0,0,  0,6,0},

			{8,0,0,  0,6,0,  0,0,3},
			{4,0,0,  8,0,3,  0,0,1},
			{7,0,0,  0,2,0,  0,0,6},

			{0,6,0,  0,0,0,  2,8,0},
			{0,0,0,  4,1,9,  0,0,5},
			{0,0,0,  0,8,0,  0,7,9}};

		System.out.println(Arrays.deepToString(initial));

		Board b = new Board(initial, initial.length);
    }
}
